name: jubank
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  connectivity: ^3.0.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_analytics: ^10.2.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  http: ^0.13.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
