name: jubank
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.1
  cloud_firestore: ^4.5.1
  connectivity: ^3.0.6
  dartz: ^0.10.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_modular: ^5.0.3
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.13.0
  freezed: ^2.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/juban.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  web:
    generate: true
    image_path: "assets/juban.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/juban.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/juban.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

